# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run package:unix
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/ # or path/to/artifact
        
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: ${{ format('{0}.zip', ${GITHUB_REF#refs/tags/}) }}
        exclusions: '*.git* /*node_modules/* .editorconfig'
