# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run package:unix
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/ # or path/to/artifact
        
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Archive Name
      id: archive_name
      run: echo "ARCHIVE_NAME=${{ format('{0}.zip', steps.branch_name.outputs.SOURCE_TAG) }}" >> $GITHUB_OUTPUT

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        path: 'dist/'
        filename: ${{ steps.archive_name.outputs.ARCHIVE_NAME }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.archive_name.outputs.ARCHIVE_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
